language: python
python: 3.5
sudo: required
virtualenv:
    system_site_packages: true
before_install:
    - "SITE_PKG_DIR=$VIRTUAL_ENV/lib/python$TRAVIS_PYTHON_VERSION/site-packages"
    - "rm -f $VIRTUAL_ENV/lib/python$TRAVIS_PYTHON_VERSION/no-global-site-packages.txt"
install:
    - "sudo apt-get install python3-numpy"
    - "sudo apt-get install python3-scipy"
    - "pip3.5 install tqdm"
    - "pip3.5 install enforce"
    - "pip3.5 install pytest"
script: "py.test"
