language: python
python: 3.5
before_install:
    - "pip3.5 install setuptools --upgrade"
install:
    - "pip3.5 install --egg llvmlite"
    - "pip3.5 install numpy"
    - "pip3.5 install scipy"
    - "pip3.5 install tqdm"
    - "pip3.5 install numba"
    - "pip3.5 install enforce"
    - "pip3.5 install pytest"
script: "py.test"
