language: python
python: 3.5
before_install:
    - "pip3.5 install setuptools --upgrade"
install:
    - "pip install llvmlite"
    - "pip install numpy"
    - "pip install scipy"
    - "pip install tqdm"
    - "pip install numba"
    - "pip install enforce"
    - "pip install pytest"
script: "py.test"
